### ISSUE TITLE
如何实现路由鉴权？

### ISSUE THREAD

**Issue by nothinggift** [fluttercandies/ff_annotation_route#22]
通过注释生成路由的库目前好像只有这个还在维护了，请问在使用这个库的基础下如何实现路由的鉴权？

**Comment by AlexV525** [comment]
请详细说明鉴权的场景及期待的实现。

**Comment by zmtzawqlp** [comment]
建议加群讨论，大家正在聊这个问题

**Comment by nothinggift** [comment]
这应该是非常常见的使用场景，举例来说app内有部分页面只允许已登录用户访问，当路由跳转到这些页面前，会执行一次检查，如果没有登录则replace到登录页面

这个检查应该在访问对应路由前执行，所以检查方法不能放在目标页面里

他的实现可以是增加一个 route guards参数，可以传入多个已经注册的方法名

鉴权方法接受源路由与目标路由参数，返回一个路由名或者widget。如果返回true/false，则需要预先定义fallback route。

**Comment by nothinggift** [comment]
> 建议加群讨论，大家正在聊这个问题

群是？

**Comment by AlexV525** [comment]
> 这个检查应该在访问对应路由前执行，所以检查方法不能放在目标页面里

其实对于Flutter来说，对于路由的检查其实是**不够符合**Flutter Style的。鉴权**可以且应当**封装在操作点上，而不是与路由强耦合。

举个例子：
```dart
class ShouldLogin extends StatelessWidget {
  const ShouldLogin({
    Key key,
    @required this.child,
  })  : assert(child != null, "Child cannot be null in ShouldLogin."),
        super(key: key);

  final Widget child;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      behavior: HitTestBehavior.opaque,
      onTap: SettingUtils.isLogin // 在这里判断是否有你需要的权限，或直接抽离成对应方法进行处理
          ? null
          : () => navigatorState.pushNamed(Routes.LOGIN_PAGE),
      child: AbsorbPointer(absorbing: !SettingUtils.isLogin, child: child),
    );
  }
}
```
使用时通过`ShouldLogin(child: yourWidget)`嵌套即可。对于**Everything is a Widget**的Flutter来说，这应该是个更加合适的解决方案。

另外，请时刻注意本组件是注解路由，其核心在于通过注解方便地生成路由并提供给`Navigator`使用，而不是耦合业务层逻辑。

**Comment by nothinggift** [comment]
[auto_route](https://pub.dev/packages/auto_route) ， [sailor](https://pub.dev/packages/sailor)中都有这种实现，你可以参考下，我只是认为注解可能比那两种更方便一些，实际测试下来，发现这个生成过程与build_runner相比有些痛苦

如果你认为注解路由不应该支持这种业务侧逻辑的话，那确实没必要做这个

但是你举的例子是一个常见的错误，因为通向这些被保护的路由的入口在实际软件中是大量存在且分散的，在所有触发跳转逻辑的按钮上进行鉴权是非常难以维护且低效的，这和是否是widget并没有关系，而是route guards本身就只适合在路由层实现。

**Comment by AlexV525** [comment]
> 如果你认为注解路由不应该支持这种业务侧逻辑的话，那确实没必要做这个

的确不同于目前的开发方向，我们会讨论下是否增加这种支持。

> 但是你举的例子是一个常见的错误，因为通向这些被保护的路由的入口在实际软件中是大量存在且分散的，在所有触发跳转逻辑的按钮上进行鉴权是非常难以维护且低效的

感谢指正，但可能我从我自己的业务角度来谈有不同的想法，我会重新思考对于鉴权的处理问题，不过个人目前阶段还是认为对操作点做控制是非常有必要的，同时也不局限于操作，请求也是其内容之一。

> 群是？

QQ群：181398081
