### ISSUE TITLE
Error: Too many positional arguments: 0 allowed, but 1 found

### ISSUE THREAD

**Issue by wangyujie1207** [fluttercandies/ff_annotation_route#24]
3.3.0 执行pub active 会出现错误 ff_annotation_route-3.3.0/lib/src/utils/ast.dart:105:85 
这行替换即可 final Scanner scanner = Scanner(source, reader, errorCollector)..configureFeatures(featureSet:featureSet);

**Comment by wangyujie1207** [comment]
好像只有低版本 升高版本会出这个问题

**Comment by wangyujie1207** [comment]
> 3.3.0 执行pub active 会出现错误 ff_annotation_route-3.3.0/lib/src/utils/ast.dart:105:85
> 这行替换即可 final Scanner scanner = Scanner(source, reader, errorCollector)..configureFeatures(featureSet:featureSet);

目前问题只存在于pub active激活中

**Comment by zmtzawqlp** [comment]
sdk不一致的问题吧。。工具一般我上的最新的

**Comment by AlexV525** [comment]
Caused by `analyzer: ^0.39.2+1` which fetched `0.39.11` with breaking changes.

**Comment by wangyujie1207** [comment]
3.1.2 升级 3.3.0   pub active 导致错误  sdk 1.17.4  macos

**Comment by zmtzawqlp** [comment]
analyzer 出breaking change了。我空了更新下

**Comment by zmtzawqlp** [comment]
你等半小时重新激活一下吧。已经修复上传了
