### ISSUE TITLE
Bug: throwing error when define argumentNames with double quotes

### ISSUE THREAD

**Issue by NarHakobyan** [fluttercandies/ff_annotation_route#6]
```dart
@FFRoute(
  name: 'rexiapp://sms-confirm',
  routeName: 'sms-confirm',
  argumentNames: ['phoneNumber'],
)
```
```
FormatException: Unexpected character (at character 2)
['phoneNumber']
```

**Comment by zmtzawqlp** [comment]
please use ' instead of " ,  dart analyzer couldn't work with double quotes

**Comment by zmtzawqlp** [comment]
It seems that it happens at  latest version of flutter sdk.

**Comment by zmtzawqlp** [comment]
plz, chang quote to double quotes, check all of annotation routes

**Comment by AlexV525** [comment]
For users who has the same issue, please be aware that you can only use double quote (") in `argumentNames` due to single quotes cannot be decoded in JSON format string. If any single quote have been provided, the `FormatException` will be thrown.

**Comment by AlexV525** [comment]
@NarHakobyan The exception might not caused by the code you wrote at here, please make sure that there're no single quotes in your arguments.

**Comment by NarHakobyan** [comment]
yeah, but I have linter which requires single quotes, it's confusing that any third party library requires to write with different code style

**Comment by NarHakobyan** [comment]
I think need to change builder, so it can parse either single quotes and double quotes

**Comment by AlexV525** [comment]
@NarHakobyan The root cause was the official `JsonDecoder`, it cannot recognized single quotes in `JSON`. You can try at [dartpad](https://dartpad.dev), with single quotes string the decoder cannot decode the string to json successfully.
```
import 'dart:convert';

void main() {
  String a = "{'something': 'somevalue'}";
  print(jsonDecode(a));
}
```
```
Uncaught Error: FormatException: SyntaxError: Unexpected token ' in JSON at position 1
```
